# Generated by Django 3.0.7 on 2021-05-13 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user1profile',
            name='phone',
        ),
    ]
