# Generated by Django 3.0.7 on 2021-05-14 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user1profile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user1profile',
            old_name='user',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='user2profile',
            old_name='user',
            new_name='users',
        ),
    ]
