# Generated by Django 3.0.7 on 2021-05-14 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210514_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user1profile',
            old_name='users',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user2profile',
            old_name='users',
            new_name='user',
        ),
    ]
