# Generated by Django 3.2.3 on 2021-05-24 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_auto_20210514_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='User6Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paytmnumber', models.CharField(blank=True, max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User5Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upiid', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User4Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcardnumber', models.CharField(blank=True, max_length=16)),
                ('dexpyear', models.CharField(blank=True, max_length=4)),
                ('dexpmonth', models.CharField(blank=True, max_length=2)),
                ('dnameoncard', models.CharField(blank=True, max_length=100)),
                ('dcvv', models.CharField(blank=True, max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User3Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccardnumber', models.CharField(blank=True, max_length=16)),
                ('cexpyear', models.CharField(blank=True, max_length=4)),
                ('cexpmonth', models.CharField(blank=True, max_length=2)),
                ('cnameoncard', models.CharField(blank=True, max_length=100)),
                ('ccvc', models.CharField(blank=True, max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
