# Generated by Django 3.2.3 on 2021-05-24 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user3profile_user4profile_user5profile_user6profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user3profile',
            old_name='ccvc',
            new_name='ccvv',
        ),
    ]
