# Generated by Django 3.2.3 on 2021-05-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210516_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
