# Generated by Django 3.0.7 on 2021-05-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_shopcart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
