# Generated by Django 3.2.3 on 2021-05-18 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210517_1046'),
        ('cart', '0006_order_delivery_charge'),
    ]

    operations = [
    ]
